<?php /** @var $block \Vendor\Module\Block\Success */ ?>
<div class="checkout-success">

    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php else: ?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif; ?>

        <!-- BEGIN VENDOR_MODULE CUSTOM -->
        <p><?php echo __('You ordered %1 items.', (int) $block->getOrder()->getTotalQtyOrdered()) ?></p>
        <!-- END VENDOR_MODULE CUSTOM -->

        <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif; ?>

    <?php echo $block->getAdditionalInfoHtml() ?>
    <?php if($block->getPaymentMethod() == 'yapay_bank_slip') :?>
        <div class="actions-toolbar">
            <div class="primary">
                <p><strong><a class="order-number" href="<?php echo $block->getUrlPayment() ?>"><span><?php /* @escapeNotVerified */ echo __('Imprima seu boleto') ?></span></a></strong></p>
            </div>
        </div>
    <?php endif; ?>
    <?php if($block->getPaymentMethod() == 'yapay_transference') :?>
        <div class="actions-toolbar">
            <div class="primary">
                <p><strong><a class="order-number" href="<?php echo $block->getUrlPayment() ?>"><span><?php /* @escapeNotVerified */ echo __('Acesse aqui para realizar a Transferência') ?></span></a></strong></p>
            </div>
        </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>